In [17]:
import numpy as np
import random


In [26]:
newArr = np.random.randint(0,10,10)
print(newArr)

[8 2 4 9 2 8 7 2 5 3]


arr = np.array([[4, 23, 98, 7, 6, 98],
         [38, 54, 6, 18, 10, 4],
         [5, 48, 4, 56, 5, 6],
         [3, 54, 6, 18, 10, 4],
         [48, 54, 6, 18, 10, 4],
         [18, 54, 6, 18, 10, 4],])


In [7]:
arr = np.array([[4, 23, 98, 7, 6, 98],
         [38, 54, 6, 18, 10, 4],
         [5, 48, 4, 56, 5, 6],
         [3, 76, 6, 18, 10, 4],
         [48, 54, 63, 19, 13, 4],
         [18, 14, 62, 16, 90, 44],
         [18, 54, 61, 11, 98, 14],])

print(np.shape(arr))

(7, 6)


Task-2

In [9]:
arr = arr.reshape((3, 14))
print(arr)

[[ 4 23 98  7  6 98 38 54  6 18 10  4  5 48]
 [ 4 56  5  6  3 76  6 18 10  4 48 54 63 19]
 [13  4 18 14 62 16 90 44 18 54 61 11 98 14]]


Task-3


In [10]:
arr1 = np.array([0, 1 ,2, 3, 4, 5, 6, 7, 8, 9])
for x in arr1:
  if(x%2!=0):
    print(x)


1
3
5
7
9


Task-4


In [14]:
arr1 = np.array([0, 1 ,2, 3, 4, 5, 6, 7, 8, 9])
for x in range(0, len(arr1)):
  if(arr1[x]%2!=0):
    arr1[x] = -1
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task-5

In [33]:
arr = np.array([0, 1 ,2, 3, 4, 5, 6, 7, 8, 9])
odd = np.zeros(10, dtype=np.int32)
for x in range(0, len(arr1)):
  odd[x] = arr[x]
  if(arr[x]%2!=0):
    odd[x] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task-6

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

for i in range(len(a)):
  if(a[i]==b[i]):
    print("In position",i,"no index the two array matches.")

In position 1 no index the two array matches.
In position 3 no index the two array matches.
In position 5 no index the two array matches.
In position 7 no index the two array matches.


Task-7

In [36]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
for i in range(len(a)):
  if a[i]>=5 and a[i]<=10:
    print(a[i])

6
9
10


Task-8

In [38]:
vector1 = np.zeros(10)
vector2 = np.ones(10)
print(vector2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
ans1 = np.concatenate((vector1, vector2), axis=0)
print(ans1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
hor = np.array([vector1, vector2])
print(hor)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Task-9

In [59]:
m = np.random.randint(0, 10, size=(4, 4))
print(m)

[[4 9 3 2]
 [1 5 8 9]
 [8 4 8 3]
 [4 4 3 6]]


Task-10

In [60]:
n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)
print("x =", x)
print("y =", y)

x = [[0.2968117  0.78272189 0.21352283 0.1328331 ]
 [0.72382484 0.03517983 0.22807551 0.82518872]
 [0.89698925 0.32876493 0.92352704 0.78272211]
 [0.36885567 0.27928923 0.46263733 0.74722031]
 [0.15559081 0.92690432 0.89915662 0.78892117]]
y = [1 1 1 0 1]


Task-11

In [65]:
def extract_subset(x,y,y0):
  x2 = x[y==y0, :]
  return x2

ans = extract_subset(x,y,1)
print(ans)

[[0.2968117  0.78272189 0.21352283 0.1328331 ]
 [0.72382484 0.03517983 0.22807551 0.82518872]
 [0.89698925 0.32876493 0.92352704 0.78272211]
 [0.15559081 0.92690432 0.89915662 0.78892117]]


Task-12

In [79]:
import csv
with open('/content/sample_data/iris.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
['5.1', '3.5', '1.4', '0.2', 'setosa']
['4.9', '3', '1.4', '0.2', 'setosa']
['4.7', '3.2', '1.3', '0.2', 'setosa']
['4.6', '3.1', '1.5', '0.2', 'setosa']
['5', '3.6', '1.4', '0.2', 'setosa']
['5.4', '3.9', '1.7', '0.4', 'setosa']
['4.6', '3.4', '1.4', '0.3', 'setosa']
['5', '3.4', '1.5', '0.2', 'setosa']
['4.4', '2.9', '1.4', '0.2', 'setosa']
['4.9', '3.1', '1.5', '0.1', 'setosa']
['5.4', '3.7', '1.5', '0.2', 'setosa']
['4.8', '3.4', '1.6', '0.2', 'setosa']
['4.8', '3', '1.4', '0.1', 'setosa']
['4.3', '3', '1.1', '0.1', 'setosa']
['5.8', '4', '1.2', '0.2', 'setosa']
['5.7', '4.4', '1.5', '0.4', 'setosa']
['5.4', '3.9', '1.3', '0.4', 'setosa']
['5.1', '3.5', '1.4', '0.3', 'setosa']
['5.7', '3.8', '1.7', '0.3', 'setosa']
['5.1', '3.8', '1.5', '0.3', 'setosa']
['5.4', '3.4', '1.7', '0.2', 'setosa']
['5.1', '3.7', '1.5', '0.4', 'setosa']
['4.6', '3.6', '1', '0.2', 'setosa']
['5.1', '3.3', '1.7', '0.5', 'setosa']
['4.

Task-13

In [122]:
import statistics
with open('/content/sample_data/iris.csv', 'r') as file:
    reader = csv.reader(file)
    ans = []
    sum =0
    for rows in reader:
          ans.append(rows[0])
    p = []
    for i in range(1, len(ans)):
        p.append(int(i))
    print("Median : ",statistics.median(p))
    print("Mean : ",statistics.mean(p))
    print("Standard Dev : ",np.std(p))

Median :  75.5
Mean :  75.5
Standard Dev :  43.300307928081374
